---
resources:
  - ../../base
  - sre-ojt-posung-chen-sample-canary-service.yaml
  - sre-ojt-posung-chen-sample-ingress.yaml
configMapGenerator:
  - name: sre-ojt-posung-chen-sample
    envs:
      - sre-ojt-posung-chen-sample.properties
    behavior: merge
patchesStrategicMerge:
  - patch.yaml
images:
  - name: docker.paypay.ne.jp/sre-ojt-posung-chen-sample
    newTag: "v0.0.3"
commonAnnotations:
  reloaded: "1"
